apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  labels:
    app: mern-backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      imagePullSecrets:
        - name:  ecr-registry-secret
      containers:
      - name: mern-backend-container
        image: 688567300982.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        imagePullPolicy: Always        
        ports:
        - containerPort: 3500 
        env:
          - name: MONGO_CONN_STR
            value: mongodb://db-service:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password