apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  labels:
    app: mern-backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      imagePullSecrets:
        - name:  ecr-registry-secret
      containers:
      - name: mern-backend-container
        image: 688567300982.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080           
        env:
          - name:  DB_USERNAME
            valueFrom:
              secretKeyRef:
                name:  db-secret
                key:  username
          - name:  DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  db-secret
                key:  password
          - name:  DB_DATABASE
            valueFrom:
              secretKeyRef:
                name:  db-secret
                key:  database
          - name: DB_SERVICE
            value: db-service 
      livenessProbe:
          httpGet: 
             path: /healthz
             port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
      readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      startupProbe:
          httpGet:
            path: /started
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
      